spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/virtualclothingstore
    username: postgres
    password: password
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin:9411